### ISSUE TITLE
Endpoint for Adding a mentor and Model

### ISSUE THREAD

**Issue by rakaar** [kossiitkgp/kwoc20-backend#2]
- In `models/models.go`, Add a Mentor Model.  The schema is [here](https://dbdiagram.io/d/5ed86a4c39d18f555300363a) . For reference, look at the project model in the same file
- Complete the function `MentorReg` in `routes/mentor.go`
- The function should take a JSON, unmarshal it, Add the data to DB. For reference look at the `ProjectReg` function in `routes/project.go`.

**Comment by grapheo12** [comment]
Closed by #4
