### ISSUE TITLE
Let's complete UserOAuth[part1]

### ISSUE THREAD

**Issue by rakaar** [kossiitkgp/kwoc20-backend#24]
After we get user's GitHub username from [this](https://github.com/kossiitkgp/kwoc20-backend/blob/master/controllers/UserOAuth.go#L72) variable 
Using the username, check if the user already exists or not,
**if a new user**: 
Add the username in the database from the ["login" key](https://github.com/kossiitkgp/kwoc20-backend/blob/master/controllers/UserOAuth.go#L74) 
Send a JSON to the frontend in this format
{ "username" : "string", "name": "string", "email" : "string", "type" :"mentor or student based on state as shown [here](https://github.com/kossiitkgp/kwoc20-backend/blob/master/controllers/UserOAuth.go#L32)", 
"reg_type" : "new" }

You can obtain the key names from lines after [this](https://github.com/kossiitkgp/kwoc20-backend/blob/master/controllers/UserOAuth.go#L74)

Explanation of some pairs
- the "type" will telll whether its a mentor or not
- the "reg_type" will tell whether user should be redirected to dashboard or a form where name and email needs to be filed. Since reg_type is new, the user wll be redirected to form.

If the user already exists,
it involves JWT hence lets make it in another issue,

PS - before u startworking on the UserOAuth.go,, please change the variable names appropirately like at many places it is written mentor1, mentorOAuth, at such places make it userOAuth please

**Comment by grapheo12** [comment]
I guess even if the user is new, you need to send the JWT back, right?
So I think it'd be better to send back an uniform response like:

```js
{
    ...whateverYouSaid,
    jwt: signedToken
}
```

In this way, you can get all the necessary information required for logging the user in.

**Comment by rakaar** [comment]
@grapheo12 
- there have been discussions on whether still or not to use JWT 
- If a new user, why to send a JWT immeditately, we need to get the user's email and Name first?
What if the user doesn't provide email?

so this was the actual plan
If a new user redirect to a page where  we will show name and email that we got from github (some times we dont get email from github and sometimes user might want to change their mail)
After user enters these creds, they will be sent to a new endpoint and in return he will get the session/Jwt token there.

**Comment by grapheo12** [comment]
Ok ok understood. I am implementing both modes. You can modify the contents of the JWT later.
The response format will be:
```js
{
      ...whateveryousaid,
      isNewUser: bool,
      jwt: string
}
```
for all modes. If isNewUser is true, we will send an empty JWT.
I guess this endpoint will not add people to DB then, right?

**Comment by grapheo12** [comment]
You can remove / change the JWT part if you change the Authentication mechanism.
